name: CI - Analyse SonarCloud

on:
  workflow_call:

jobs:
  sonar-analysis:
    name: Analyse SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test Backend
        working-directory: back
        run: |
          mvn clean test
          mvn jacoco:report

      - name: Package Backend
        working-directory: back
        run: mvn package -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: front
        run: npm ci

      - name: Build and Test Frontend
        working-directory: front
        run: |
          npm run build --if-present
          npm run coverage

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=killiadmin_bobapp
            -Dsonar.organization=killiadmin
            -Dsonar.sources=back/src/main/java,front/src
            -Dsonar.tests=back/src/test/java,front/src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.exclusions=**/node_modules/**,**/test/**,**/*.spec.ts
            -Dsonar.coverage.exclusions=**/environment*.ts,**/main.ts,**/test.ts,**/polyfills.ts
            -Dsonar.java.binaries=back/target/classes
            -Dsonar.java.libraries=back/target/*.jar
            -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
            -Dsonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info
            -Dsonar.qualitygate.wait=true
